# Generated by Django 4.0.2 on 2022-02-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=10)),
                ('room', models.IntegerField(verbose_name=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.movie')),
            ],
        ),
    ]
