# Generated by Django 4.0.2 on 2022-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_drink_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.IntegerField(verbose_name=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name=3),
        ),
    ]
