# Generated by Django 4.0.2 on 2022-02-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_movieschedules_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketSold',
            new_name='Tickets',
        ),
    ]
